// Date: 20/10/2014 17:23:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package QuantaCraft.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
public class CableModel extends ModelBase
{
  //fields
    ModelRenderer PipeBottom;
    ModelRenderer PipeTop;
    ModelRenderer PipeLeft;
    ModelRenderer PipeRight;
    ModelRenderer PipeFront;
    ModelRenderer PipeBack;
    ModelRenderer PipeMiddle;
    
  public CableModel()
  {
    textureWidth = 32;
    textureHeight = 32;
    
    PipeBottom = new ModelRenderer(this, 0, 0);
    PipeBottom.addBox(0F, 0F, 0F, 3, 16, 3);
    PipeBottom.setRotationPoint(-1.5F, 32F, -1.5F);
    PipeBottom.setTextureSize(32, 32);
    PipeBottom.mirror = true;
    setRotation(PipeBottom, 0F, 0F, 0F);
    PipeTop = new ModelRenderer(this, 0, 0);
    PipeTop.addBox(0F, 0F, 0F, 3, 16, 3);
    PipeTop.setRotationPoint(-1.5F, 16F, -1.5F);
    PipeTop.setTextureSize(32, 32);
    PipeTop.mirror = true;
    setRotation(PipeTop, 0F, 0F, 0F);
    PipeLeft = new ModelRenderer(this, 0, 0);
    PipeLeft.addBox(0F, 0F, 0F, 3, 16, 3);
    PipeLeft.setRotationPoint(-1.5F, 33.5F, 0F);
    PipeLeft.setTextureSize(32, 32);
    PipeLeft.mirror = true;
    setRotation(PipeLeft, 1.570796F, 0F, 0F);
    PipeRight = new ModelRenderer(this, 0, 0);
    PipeRight.addBox(0F, 0F, 0F, 3, 16, 3);
    PipeRight.setRotationPoint(-1.5F, 33.5F, -16F);
    PipeRight.setTextureSize(32, 32);
    PipeRight.mirror = true;
    setRotation(PipeRight, 1.570796F, 0F, 0F);
    PipeFront = new ModelRenderer(this, 0, 0);
    PipeFront.addBox(0F, 0F, 0F, 3, 16, 3);
    PipeFront.setRotationPoint(0F, 33.5F, -1.5F);
    PipeFront.setTextureSize(32, 32);
    PipeFront.mirror = true;
    setRotation(PipeFront, 1.570796F, -1.570796F, 0F);
    PipeBack = new ModelRenderer(this, 0, 0);
    PipeBack.addBox(0F, 0F, 0F, 3, 16, 3);
    PipeBack.setRotationPoint(16F, 33.5F, -1.5F);
    PipeBack.setTextureSize(32, 32);
    PipeBack.mirror = true;
    setRotation(PipeBack, 1.570796F, -1.570796F, 0F);
    PipeMiddle = new ModelRenderer(this, 12, 0);
    PipeMiddle.addBox(0F, 0F, 0F, 3, 3, 3);
    PipeMiddle.setRotationPoint(-1.5F, 30.5F, -1.5F);
    PipeMiddle.setTextureSize(32, 32);
    PipeMiddle.mirror = true;
    setRotation(PipeMiddle, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {

  }
  
  public void renderCable(int a,Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
	// super.render(entity, f, f1, f2, f3, f4, f5);
	  
	 switch(a){
	 default: return;
	 case 1:
    PipeBottom.render(f5);
    break;
	 case 0:
    PipeTop.render(f5);
    break;
	 case 4:
    PipeLeft.render(f5);
    break;
	 case 5:
    PipeRight.render(f5);
    break;
	 case 2:
    PipeFront.render(f5);
    break;
	 case 3:
    PipeBack.render(f5);
    break;
	 case 6:
		 PipeMiddle.render(f5);
		 break;
	 }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,null);
  }

}
