// Date: 13/10/2014 14:55:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package QuantaCraft.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ConTableModel extends ModelBase
{
  //fields
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Table;
    ModelRenderer BookBase;
    ModelRenderer BookOut1;
    ModelRenderer Shape1;
  
  public ConTableModel()
  {
	  textureWidth = 128;
	  textureHeight = 64;
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(-8F, 27F, -8F, 2, 24, 2);
      Leg1.setRotationPoint(10.6F, -2F, 8F);
      Leg1.setTextureSize(128, 64);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, -0.2094395F);
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(-8F, 27F, -8F, 2, 24, 2);
      Leg2.setRotationPoint(3F, 1F, 7F);
      Leg2.setTextureSize(128, 64);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0.2094395F);
      Leg3 = new ModelRenderer(this, 0, 0);
      Leg3.addBox(-8F, 27F, -8F, 2, 24, 2);
      Leg3.setRotationPoint(7F, -2F, 11.2F);
      Leg3.setTextureSize(128, 64);
      Leg3.mirror = true;
      setRotation(Leg3, 0.2094395F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 0);
      Leg4.addBox(-8F, 27F, -8F, 2, 24, 2);
      Leg4.setRotationPoint(7F, 1F, 3F);
      Leg4.setTextureSize(128, 64);
      Leg4.mirror = true;
      setRotation(Leg4, -0.2094395F, 0F, 0F);
      Table = new ModelRenderer(this, 0, 0);
      Table.addBox(-8F, 27F, -8F, 32, 3, 32);
      Table.setRotationPoint(-8F, -1.866667F, -8F);
      Table.setTextureSize(128, 64);
      Table.mirror = true;
      setRotation(Table, 0F, 0F, 0F);
      BookBase = new ModelRenderer(this, 0, 35);
      BookBase.addBox(-8F, 27F, -8F, 14, 5, 18);
      BookBase.setRotationPoint(0F, -7F, 0F);
      BookBase.setTextureSize(128, 64);
      BookBase.mirror = true;
      setRotation(BookBase, 0F, 0F, 0F);
      BookOut1 = new ModelRenderer(this, 64, 35);
      BookOut1.addBox(-8F, 27F, -8F, 1, 3, 18);
      BookOut1.setRotationPoint(-1F, -6F, 0F);
      BookOut1.setTextureSize(128, 64);
      BookOut1.mirror = true;
      setRotation(BookOut1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-8F, 27F, -8F, 1, 1, 1);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Table.render(f5);
    //BookBase.render(f5);
    //BookOut1.render(f5);
    //Shape1.render(f5);
  }
  
  public void renderWithBook(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Table.render(f5);
    BookBase.render(f5);
    BookOut1.render(f5);
    //Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,null);
  }

}
