package QuantaCraft.render;

import QuantaCraft.main.modMain;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
// Date: 16/11/2014 20:13:28
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;







public class ModelTankBlock extends ModelBase
{
  //fields
    ModelRenderer TankSide1;
    ModelRenderer TankSide2;
    ModelRenderer TankSide3;
    ModelRenderer TankSide4;
    ModelRenderer TankTop;
    ModelRenderer TankBottom;
  
  public ModelTankBlock()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      TankSide1 = new ModelRenderer(this, -16, -16);
      TankSide1.addBox(0F, 0F, 0F, 0, 16, 16);
      TankSide1.setRotationPoint(-8F, 8F, -8F);
      TankSide1.setTextureSize(64, 32);
      TankSide1.mirror = true;
      setRotation(TankSide1, 0F, 0F, 0F);
      TankSide2 = new ModelRenderer(this, -16, -16);
      TankSide2.addBox(0F, 0F, 0F, 0, 16, 16);
      TankSide2.setRotationPoint(8F, 8F, -8F);
      TankSide2.setTextureSize(64, 32);
      TankSide2.mirror = true;
      setRotation(TankSide2, 0F, 0F, 0F);
      TankSide3 = new ModelRenderer(this, -16, 0);
      TankSide3.addBox(0F, 0F, 0F, 16, 16, 0);
      TankSide3.setRotationPoint(-8F, 8F, -8F);
      TankSide3.setTextureSize(64, 32);
      TankSide3.mirror = true;
      setRotation(TankSide3, 0F, 0F, 0F);
      TankSide4 = new ModelRenderer(this, -16, 0);
      TankSide4.addBox(0F, 0F, 0F, 16, 16, 0);
      TankSide4.setRotationPoint(-8F, 8F, 8F);
      TankSide4.setTextureSize(64, 32);
      TankSide4.mirror = true;
      setRotation(TankSide4, 0F, 0F, 0F);
      TankTop = new ModelRenderer(this, -16, 0);
      TankTop.addBox(0F, 0F, 0F, 16, 0, 16);
      TankTop.setRotationPoint(-8F, 8F, -8F);
      TankTop.setTextureSize(64, 32);
      TankTop.mirror = true;
      setRotation(TankTop, 0F, 0F, 0F);
      TankBottom = new ModelRenderer(this, -16, 0);
      TankBottom.addBox(0F, 0F, 0F, 16, 0, 16);
      TankBottom.setRotationPoint(-8F, 24F, -8F);
      TankBottom.setTextureSize(64, 32);
      TankBottom.mirror = true;
      setRotation(TankBottom, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    ResourceLocation textures = new ResourceLocation(modMain.modid.toLowerCase() ,"textures/blocks/glass8 (" + modMain.tank.getBlockTextureFromSide(2) + ").png");
    Minecraft.getMinecraft().renderEngine.bindTexture(textures);
    TankSide1.render(f5);
    textures = new ResourceLocation(modMain.modid.toLowerCase() ,"textures/blocks/glass8 (" + modMain.tank.getBlockTextureFromSide(3) + ").png");
    Minecraft.getMinecraft().renderEngine.bindTexture(textures);
    TankSide2.render(f5);
    textures = new ResourceLocation(modMain.modid.toLowerCase() ,"textures/blocks/glass8 (" + modMain.tank.getBlockTextureFromSide(4) + ").png");
    Minecraft.getMinecraft().renderEngine.bindTexture(textures);
    TankSide3.render(f5);
    textures = new ResourceLocation(modMain.modid.toLowerCase() ,"textures/blocks/glass8 (" + modMain.tank.getBlockTextureFromSide(5) + ").png");
    Minecraft.getMinecraft().renderEngine.bindTexture(textures);
    TankSide4.render(f5);
    textures = new ResourceLocation(modMain.modid.toLowerCase() ,"textures/blocks/glass8 (" + modMain.tank.getBlockTextureFromSide(0) + ").png");
    Minecraft.getMinecraft().renderEngine.bindTexture(textures);
    TankTop.render(f5);
    textures = new ResourceLocation(modMain.modid.toLowerCase() ,"textures/blocks/glass8 (" + modMain.tank.getBlockTextureFromSide(1) + ").png");
    Minecraft.getMinecraft().renderEngine.bindTexture(textures);
    TankBottom.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
