package QuantaCraft.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.entity.Entity;

// Date: 16/11/2014 18:42:42
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX








public class ModelTank extends ModelBase
{
  //fields
    ModelRenderer Tank;
  
  public ModelTank()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Tank = new ModelRenderer(this, 0, 0);
      Tank.addBox(0F, 0F, 0F, 16, 16, 16);
      Tank.setRotationPoint(-8F, 8F, -8F);
      Tank.setTextureSize(64, 32);
      Tank.mirror = true;
      setRotation(Tank, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Tank.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
