package QuantaCraft.render;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHologramStand extends ModelBase
{
	// Date: 24/09/2014 10:51:13
	// Template version 1.1
	// Java generated by Techne
	// Keep in mind that you still need to fill in some blanks
	// - ZeuX






	

	  //fields
	    ModelRenderer Base;
	    ModelRenderer Proj1;
	    ModelRenderer Proj2;
	    ModelRenderer Proj3;
	    ModelRenderer Proj4;
	  
	  public ModelHologramStand()
	  {
	    textureWidth = 64;
	    textureHeight = 32;
	    
	      Base = new ModelRenderer(this, 0, 15);
	      Base.addBox(0F, 0F, 0F, 16, 1, 16);
	      Base.setRotationPoint(-8F, 23F, -8F);
	      Base.setTextureSize(64, 32);
	      Base.mirror = true;
	      setRotation(Base, 0F, 0F, 0F);
	      Proj1 = new ModelRenderer(this, 0, 0);
	      Proj1.addBox(0F, 0F, 0F, 1, 1, 10);
	      Proj1.setRotationPoint(4F, 22.2F, -5F);
	      Proj1.setTextureSize(64, 32);
	      Proj1.mirror = true;
	      setRotation(Proj1, 0F, 0F, 0F);
	      Proj2 = new ModelRenderer(this, 0, 0);
	      Proj2.addBox(0F, 0F, 0F, 1, 1, 10);
	      Proj2.setRotationPoint(-5F, 22.2F, -5F);
	      Proj2.setTextureSize(64, 32);
	      Proj2.mirror = true;
	      setRotation(Proj2, 0F, 0F, 0F);
	      Proj3 = new ModelRenderer(this, 0, 13);
	      Proj3.addBox(0F, 0F, 0F, 8, 1, 1);
	      Proj3.setRotationPoint(-4F, 22.2F, -5F);
	      Proj3.setTextureSize(64, 32);
	      Proj3.mirror = true;
	      setRotation(Proj3, 0F, 0F, 0F);
	      Proj4 = new ModelRenderer(this, 0, 13);
	      Proj4.addBox(0F, 0F, 0F, 8, 1, 1);
	      Proj4.setRotationPoint(-4F, 22.2F, 4F);
	      Proj4.setTextureSize(64, 32);
	      Proj4.mirror = true;
	      setRotation(Proj4, 0F, 0F, 0F);
	  }
	  
	  public void render(Entity ent,float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.render(null,f, f1, f2, f3, f4, f5);
	    setRotationAngles(f, f1, f2, f3, f4, f5);
	    Base.render(f5);
	    Proj1.render(f5);
	    Proj2.render(f5);
	    Proj3.render(f5);
	    Proj4.render(f5);
	  }
	  
	  private void setRotation(ModelRenderer model, float x, float y, float z)
	  {
	    model.rotateAngleX = x;
	    model.rotateAngleY = y;
	    model.rotateAngleZ = z;
	  }
	  
	  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	  {
	    super.setRotationAngles(f, f1, f2, f3, f4, f5,null);
	  }

	}


