// Date: 05/10/2014 16:17:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package QuantaCraft.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.RenderHelper;
import net.minecraft.entity.Entity;

public class ModelItemTransferer extends ModelBase
{
  //fields
	ModelRenderer Wall1;
	ModelRenderer Wall3;
	ModelRenderer Wall2;
	ModelRenderer Wall4;
  
  public ModelItemTransferer(int rY , int rX , int rZ)
  {
    textureWidth = 32;
    textureHeight = 32;

      Wall1 = new ModelRenderer(this, 0, 0);
      Wall1.addBox(-8F, -1F, -6F, 8, 2, 0);
      Wall1.setRotationPoint(8F, 16F, 8F);
      Wall1.setTextureSize(32, 32);
      Wall1.mirror = true;
      setRotation(Wall1, rX , rY , rZ);
      Wall3 = new ModelRenderer(this, 0, 0);
      Wall3.addBox(-8F, 1F, -8F, 8, 0, 2);
      Wall3.setRotationPoint(8F, 16F, 8F);
      Wall3.setTextureSize(32, 32);
      Wall3.mirror = true;
      setRotation(Wall3, rX , rY , rZ);
      Wall2 = new ModelRenderer(this, 0, 0);
      Wall2.addBox(-8F, -1F,-8F, 8, 0, 2);
      Wall2.setRotationPoint(8F, 16F, 8F);
      Wall2.setTextureSize(32, 32);
      Wall2.mirror = true;
      setRotation(Wall2, rX , rY , rZ);
      Wall4 = new ModelRenderer(this, 0, 0);
      Wall4.addBox(-8F, -1F, -8F, 8, 2, 0);
      Wall4.setRotationPoint(8F, 16F, 8f);
      Wall4.setTextureSize(32, 32);
      Wall4.mirror = true;
      setRotation(Wall4, rX , rY , rZ);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, null);
    Wall1.render(f5);
    Wall3.render(f5);
    Wall2.render(f5);
    Wall4.render(f5);
  }
  
  public void renderCable(float f, float f1, float f2, float f3, float f4, float f5 , int type){
	  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
