// Date: 12/11/2014 20:49:16
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package QuantaCraft.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.entity.Entity;

public class SmartChestModel extends ModelBase
{
  //fields
    ModelRenderer Bottom;
    ModelRenderer Top;
    ModelRenderer Tenderil1;
    ModelRenderer Tenderil2;
    ModelRenderer Tenderil3;
    ModelRenderer Tenderil4;
  
  public SmartChestModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Bottom = new ModelRenderer(this, 0, 0);
      Bottom.addBox(0F, 0F, 0F, 16, 3, 16);
      Bottom.setRotationPoint(-8F, 21F, -8F);
      Bottom.setTextureSize(64, 64);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(0F, 0F, 0F, 16, 3, 16);
      Top.setRotationPoint(-8F, 8F, -8F);
      Top.setTextureSize(64, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Tenderil1 = new ModelRenderer(this, 0, 19);
      Tenderil1.addBox(0F, 0F, 0F, 2, 10, 2);
      Tenderil1.setRotationPoint(5F, 11F, 5F);
      Tenderil1.setTextureSize(64, 64);
      Tenderil1.mirror = true;
      setRotation(Tenderil1, 0F, 0F, 0F);
      Tenderil2 = new ModelRenderer(this, 0, 19);
      Tenderil2.addBox(0F, 0F, 0F, 2, 10, 2);
      Tenderil2.setRotationPoint(-7F, 11F, 5F);
      Tenderil2.setTextureSize(64, 64);
      Tenderil2.mirror = true;
      setRotation(Tenderil2, 0F, 0F, 0F);
      Tenderil3 = new ModelRenderer(this, 0, 19);
      Tenderil3.addBox(0F, 0F, 0F, 2, 10, 2);
      Tenderil3.setRotationPoint(-7F, 11F, -7F);
      Tenderil3.setTextureSize(64, 64);
      Tenderil3.mirror = true;
      setRotation(Tenderil3, 0F, 0F, 0F);
      Tenderil4 = new ModelRenderer(this, 0, 19);
      Tenderil4.addBox(0F, 0F, 0F, 2, 10, 2);
      Tenderil4.setRotationPoint(5F, 11F, -7F);
      Tenderil4.setTextureSize(64, 64);
      Tenderil4.mirror = true;
      setRotation(Tenderil4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Bottom.render(f5);
    Top.render(f5);
    Tenderil1.render(f5);
    Tenderil2.render(f5);
    Tenderil3.render(f5);
    Tenderil4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }
  

}
